# Local Command - act -j gen-orval
name: Sync App API Schema with OpenAPI Spec

on:
  push:
    paths:
      - openapi.yaml
      - scripts/orval-cleanup.ts
      - .github/workflows/gen-orval.yaml
      - orval.config.ts
  workflow_dispatch:

# Generate Orval Artifacts
# so that our script runs the same way as it does locally
jobs:
  gen-orval:
    # Runner images - https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - run: pnpm i -g @antfu/ni
      - run: nci

      - name: Generate Orval
        run: pnpm generate-orval

      - name: Check for changes
        id: get_changed_files
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          output: ', '

      - name: Early exit if no changes
        if: steps.get_changed_files.outputs.files == ''
        run: |
          echo '✅ No changes to the OpenAPI spec or Orval config'
          exit 0

      - name: Commit any API Client Updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: Sync code with Official OpenAPI Spec'
