name: Sync OpenAPI Schema

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch: # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full commit history

      - name: Add upstream repo
        run: git remote add upstream https://github.com/openai/openai-openapi.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Checkout only openapi.yaml history
        run: |
          git fetch upstream master  # Explicitly fetch master branch
          git checkout -b upstream-changes upstream/master
          git checkout main -- .
          git checkout upstream-changes -- openapi.yaml

      - name: Commit changes (if any)
        id: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add openapi.yaml
          git diff-index --quiet HEAD || git commit -m "chore: update OpenAPI schema from upstream"

      - name: Push changes
        if: steps.commit.outcome == 'success'
        run: git push origin main
