name: Sync OpenAPI Spec

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Latest Spec
        run: |
          curl -s https://raw.githubusercontent.com/openai/openai-openapi/refs/heads/master/openapi.yaml > openapi.yaml

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update OpenAPI spec'
